# -*- mode: ruby -*-

ISO = "generic/ubuntu2004"
NET = "192.168.56."
DOMAIN = ".netology"
HOST_PREFIX = "server"
INVENTORY_PATH = "./ansible/inventory"
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

servers = [
  {
    :hostname => HOST_PREFIX + "1" + DOMAIN,
    :ip => NET + "11",
    :ssh_host => "20011",
    :ssh_vm => "22",
    :nginx_host => "8080",
    :nginx_vm => "80",
    :prometheus_host => "3000",
    :prometheus_vm => "3000",
    :postgre_host => "5432",
    :postgre_vm => "5432",
    :ram => 1024,
    :core => 1
  }
]


Vagrant.configure(2) do |config|

  config.vm.synced_folder "H:\\data\\devops-netology\\virtualization", "/vagrant", disabled: false
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = ISO
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
 
      node.vm.network :forwarded_port, guest: machine[:ssh_vm], host: machine[:ssh_host]
      node.vm.network :forwarded_port, guest: machine[:nginx_vm], host: machine[:nginx_host]
      node.vm.network :forwarded_port, guest: machine[:prometheus_vm], host: machine[:prometheus_host]
      node.vm.network :forwarded_port, guest: machine[:postgre_vm], host: machine[:postgre_host]
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
        vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
        vb.name = machine[:hostname]
      end
          
     
        provisioner =  Vagrant::Util::Platform.windows? ? :guest_ansible : :ansible

          node.vm.provision "ansible_local" do |setup|
            #setup.inventory_path = INVENTORY_PATH
            setup.playbook = "./ansible/provision.yml"
            setup.become = true
            setup.extra_vars = { ansible_user: 'vagrant' }
          end
        # else
        #   node.vm.provision :ansible do |setup|
        #     setup.playbook = "./ansible/provision.yml"
        #     setup.become = true
        #     setup.extra_vars = { ansible_user: 'vagrant' }
        #   end
        
        

          # node.vm.provision "ansible" do |setup|
      #   setup.inventory_path = INVENTORY_PATH
      #   setup.playbook = "./ansible/provision.yml"
      #   setup.become = true
      #   setup.extra_vars = { ansible_user: 'vagrant' }
      # end
    end
  end
end

# -*- mode: ruby -*-
# vi: set ft=ruby :



